


#define U8G_FONT_TABLE_ENTRY(font)
#define U8G_FONT_TABLE                          \
    U8G_FONT_TABLE_ENTRY(font_04b_03b)		\
    U8G_FONT_TABLE_ENTRY(font_04b_03bn)		\
    U8G_FONT_TABLE_ENTRY(font_04b_03br)		\
    U8G_FONT_TABLE_ENTRY(font_04b_03)		\
    U8G_FONT_TABLE_ENTRY(font_04b_03n)		\
    U8G_FONT_TABLE_ENTRY(font_04b_03r)		\
    U8G_FONT_TABLE_ENTRY(font_04b_24)		\
    U8G_FONT_TABLE_ENTRY(font_04b_24n)		\
    U8G_FONT_TABLE_ENTRY(font_04b_24r)		\
    U8G_FONT_TABLE_ENTRY(font_10x20_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_10x20_75r)		\
    U8G_FONT_TABLE_ENTRY(font_10x20_78_79)		\
    U8G_FONT_TABLE_ENTRY(font_10x20)		\
    U8G_FONT_TABLE_ENTRY(font_10x20r)		\
    U8G_FONT_TABLE_ENTRY(font_4x6)		\
    U8G_FONT_TABLE_ENTRY(font_4x6r)		\
    U8G_FONT_TABLE_ENTRY(font_5x7)		\
    U8G_FONT_TABLE_ENTRY(font_5x7r)		\
    U8G_FONT_TABLE_ENTRY(font_5x8)		\
    U8G_FONT_TABLE_ENTRY(font_5x8r)		\
    U8G_FONT_TABLE_ENTRY(font_6x10)		\
    U8G_FONT_TABLE_ENTRY(font_6x10r)		\
    U8G_FONT_TABLE_ENTRY(font_6x12_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_6x12_75r)		\
    U8G_FONT_TABLE_ENTRY(font_6x12_78_79)		\
    U8G_FONT_TABLE_ENTRY(font_6x12)		\
    U8G_FONT_TABLE_ENTRY(font_6x12r)		\
    U8G_FONT_TABLE_ENTRY(font_6x13_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_6x13_75r)		\
    U8G_FONT_TABLE_ENTRY(font_6x13_78_79)		\
    U8G_FONT_TABLE_ENTRY(font_6x13B)		\
    U8G_FONT_TABLE_ENTRY(font_6x13Br)		\
    U8G_FONT_TABLE_ENTRY(font_6x13)		\
    U8G_FONT_TABLE_ENTRY(font_6x13O)		\
    U8G_FONT_TABLE_ENTRY(font_6x13Or)		\
    U8G_FONT_TABLE_ENTRY(font_6x13r)		\
    U8G_FONT_TABLE_ENTRY(font_7x13_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_7x13_75r)		\
    U8G_FONT_TABLE_ENTRY(font_7x13B)		\
    U8G_FONT_TABLE_ENTRY(font_7x13Br)		\
    U8G_FONT_TABLE_ENTRY(font_7x13)		\
    U8G_FONT_TABLE_ENTRY(font_7x13O)		\
    U8G_FONT_TABLE_ENTRY(font_7x13Or)		\
    U8G_FONT_TABLE_ENTRY(font_7x13r)		\
    U8G_FONT_TABLE_ENTRY(font_7x14B)		\
    U8G_FONT_TABLE_ENTRY(font_7x14Br)		\
    U8G_FONT_TABLE_ENTRY(font_7x14)		\
    U8G_FONT_TABLE_ENTRY(font_7x14r)		\
    U8G_FONT_TABLE_ENTRY(font_8x13_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_8x13_75r)		\
    U8G_FONT_TABLE_ENTRY(font_8x13B)		\
    U8G_FONT_TABLE_ENTRY(font_8x13Br)		\
    U8G_FONT_TABLE_ENTRY(font_8x13)		\
    U8G_FONT_TABLE_ENTRY(font_8x13O)		\
    U8G_FONT_TABLE_ENTRY(font_8x13Or)		\
    U8G_FONT_TABLE_ENTRY(font_8x13r)		\
    U8G_FONT_TABLE_ENTRY(font_9x15_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_9x15_75r)		\
    U8G_FONT_TABLE_ENTRY(font_9x15_78_79)		\
    U8G_FONT_TABLE_ENTRY(font_9x15B)		\
    U8G_FONT_TABLE_ENTRY(font_9x15Br)		\
    U8G_FONT_TABLE_ENTRY(font_9x15)		\
    U8G_FONT_TABLE_ENTRY(font_9x15r)		\
    U8G_FONT_TABLE_ENTRY(font_9x18_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_9x18_75r)		\
    U8G_FONT_TABLE_ENTRY(font_9x18_78_79)		\
    U8G_FONT_TABLE_ENTRY(font_9x18B)		\
    U8G_FONT_TABLE_ENTRY(font_9x18Br)		\
    U8G_FONT_TABLE_ENTRY(font_9x18)		\
    U8G_FONT_TABLE_ENTRY(font_9x18r)		\
    U8G_FONT_TABLE_ENTRY(font_baby)		\
    U8G_FONT_TABLE_ENTRY(font_babyn)		\
    U8G_FONT_TABLE_ENTRY(font_babyr)		\
    U8G_FONT_TABLE_ENTRY(font_blipfest_07)		\
    U8G_FONT_TABLE_ENTRY(font_blipfest_07n)		\
    U8G_FONT_TABLE_ENTRY(font_blipfest_07r)		\
    U8G_FONT_TABLE_ENTRY(font_chikita)		\
    U8G_FONT_TABLE_ENTRY(font_chikitan)		\
    U8G_FONT_TABLE_ENTRY(font_chikitar)		\

/**
    U8G_FONT_TABLE_ENTRY(font_courB08)		\
    U8G_FONT_TABLE_ENTRY(font_courB08r)		\
    U8G_FONT_TABLE_ENTRY(font_courB10)		\
    U8G_FONT_TABLE_ENTRY(font_courB10r)		\
    U8G_FONT_TABLE_ENTRY(font_courB12)		\
    U8G_FONT_TABLE_ENTRY(font_courB12r)		\
    U8G_FONT_TABLE_ENTRY(font_courB14)		\
    U8G_FONT_TABLE_ENTRY(font_courB14r)		\
    U8G_FONT_TABLE_ENTRY(font_courB18)		\
    U8G_FONT_TABLE_ENTRY(font_courB18r)		\
    U8G_FONT_TABLE_ENTRY(font_courB24)		\
    U8G_FONT_TABLE_ENTRY(font_courB24r)		\
    U8G_FONT_TABLE_ENTRY(font_courB24n)		\
    U8G_FONT_TABLE_ENTRY(font_courR08)		\
    U8G_FONT_TABLE_ENTRY(font_courR08r)		\
    U8G_FONT_TABLE_ENTRY(font_courR10)		\
    U8G_FONT_TABLE_ENTRY(font_courR10r)		\
    U8G_FONT_TABLE_ENTRY(font_courR12)		\
    U8G_FONT_TABLE_ENTRY(font_courR12r)		\
    U8G_FONT_TABLE_ENTRY(font_courR14)		\
    U8G_FONT_TABLE_ENTRY(font_courR14r)		\
    U8G_FONT_TABLE_ENTRY(font_courR18)		\
    U8G_FONT_TABLE_ENTRY(font_courR18r)		\
    U8G_FONT_TABLE_ENTRY(font_courR24)		\
    U8G_FONT_TABLE_ENTRY(font_courR24n)		\
    U8G_FONT_TABLE_ENTRY(font_courR24r)		\
    U8G_FONT_TABLE_ENTRY(font_cu12_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_cu12_75r)		\
    U8G_FONT_TABLE_ENTRY(font_cu12)		\
    U8G_FONT_TABLE_ENTRY(font_cursor)		\
    U8G_FONT_TABLE_ENTRY(font_cursorr)		\
    U8G_FONT_TABLE_ENTRY(font_fixed_v0)		\
    U8G_FONT_TABLE_ENTRY(font_fixed_v0n)		\
    U8G_FONT_TABLE_ENTRY(font_fixed_v0r)		\
    U8G_FONT_TABLE_ENTRY(font_freedoomr10r)		\
    U8G_FONT_TABLE_ENTRY(font_freedoomr25n)		\
    U8G_FONT_TABLE_ENTRY(font_fub11)		\
    U8G_FONT_TABLE_ENTRY(font_fub11n)		\
    U8G_FONT_TABLE_ENTRY(font_fub11r)		\
    U8G_FONT_TABLE_ENTRY(font_fub14)		\
    U8G_FONT_TABLE_ENTRY(font_fub14n)		\
    U8G_FONT_TABLE_ENTRY(font_fub14r)		\
    U8G_FONT_TABLE_ENTRY(font_fub17)		\
    U8G_FONT_TABLE_ENTRY(font_fub17n)		\
    U8G_FONT_TABLE_ENTRY(font_fub17r)		\
    U8G_FONT_TABLE_ENTRY(font_fub20)		\
    U8G_FONT_TABLE_ENTRY(font_fub20n)		\
    U8G_FONT_TABLE_ENTRY(font_fub20r)		\
    U8G_FONT_TABLE_ENTRY(font_fub25)		\
    U8G_FONT_TABLE_ENTRY(font_fub25n)		\
    U8G_FONT_TABLE_ENTRY(font_fub25r)		\
    U8G_FONT_TABLE_ENTRY(font_fub30)		\
    U8G_FONT_TABLE_ENTRY(font_fub30n)		\
    U8G_FONT_TABLE_ENTRY(font_fub30r)		\
    U8G_FONT_TABLE_ENTRY(font_fub35n)		\
    U8G_FONT_TABLE_ENTRY(font_fub42n)		\
    U8G_FONT_TABLE_ENTRY(font_fub49n)		\
    U8G_FONT_TABLE_ENTRY(font_fur11)		\
    U8G_FONT_TABLE_ENTRY(font_fur11n)		\
    U8G_FONT_TABLE_ENTRY(font_fur11r)		\
    U8G_FONT_TABLE_ENTRY(font_fur14)		\
    U8G_FONT_TABLE_ENTRY(font_fur14n)		\
    U8G_FONT_TABLE_ENTRY(font_fur14r)		\
    U8G_FONT_TABLE_ENTRY(font_fur17)		\
    U8G_FONT_TABLE_ENTRY(font_fur17n)		\
    U8G_FONT_TABLE_ENTRY(font_fur17r)		\
    U8G_FONT_TABLE_ENTRY(font_fur20)		\
    U8G_FONT_TABLE_ENTRY(font_fur20n)		\
    U8G_FONT_TABLE_ENTRY(font_fur20r)		\
    U8G_FONT_TABLE_ENTRY(font_fur25)		\
    U8G_FONT_TABLE_ENTRY(font_fur25n)		\
    U8G_FONT_TABLE_ENTRY(font_fur25r)		\
    U8G_FONT_TABLE_ENTRY(font_fur30)		\
    U8G_FONT_TABLE_ENTRY(font_fur30n)		\
    U8G_FONT_TABLE_ENTRY(font_fur30r)		\
    U8G_FONT_TABLE_ENTRY(font_fur35n)		\
    U8G_FONT_TABLE_ENTRY(font_fur42n)		\
    U8G_FONT_TABLE_ENTRY(font_fur49n)		\
    U8G_FONT_TABLE_ENTRY(font_gdb11)		\
    U8G_FONT_TABLE_ENTRY(font_gdb11n)		\
    U8G_FONT_TABLE_ENTRY(font_gdb11r)		\
    U8G_FONT_TABLE_ENTRY(font_gdb12)		\
    U8G_FONT_TABLE_ENTRY(font_gdb12n)		\
    U8G_FONT_TABLE_ENTRY(font_gdb12r)		\
    U8G_FONT_TABLE_ENTRY(font_gdb14)		\
    U8G_FONT_TABLE_ENTRY(font_gdb14n)		\
    U8G_FONT_TABLE_ENTRY(font_gdb14r)		\
    U8G_FONT_TABLE_ENTRY(font_gdb17)		\
    U8G_FONT_TABLE_ENTRY(font_gdb17n)		\
    U8G_FONT_TABLE_ENTRY(font_gdb17r)		\
    U8G_FONT_TABLE_ENTRY(font_gdb20)		\
    U8G_FONT_TABLE_ENTRY(font_gdb20n)		\
    U8G_FONT_TABLE_ENTRY(font_gdb20r)		\
    U8G_FONT_TABLE_ENTRY(font_gdb25)		\
    U8G_FONT_TABLE_ENTRY(font_gdb25n)		\
    U8G_FONT_TABLE_ENTRY(font_gdb25r)		\
    U8G_FONT_TABLE_ENTRY(font_gdb30)		\
    U8G_FONT_TABLE_ENTRY(font_gdb30n)		\
    U8G_FONT_TABLE_ENTRY(font_gdb30r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr10)		\
    U8G_FONT_TABLE_ENTRY(font_gdr10n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr10r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr11)		\
    U8G_FONT_TABLE_ENTRY(font_gdr11n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr11r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr12)		\
    U8G_FONT_TABLE_ENTRY(font_gdr12n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr12r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr14)		\
    U8G_FONT_TABLE_ENTRY(font_gdr14n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr14r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr17)		\
    U8G_FONT_TABLE_ENTRY(font_gdr17n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr17r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr20)		\
    U8G_FONT_TABLE_ENTRY(font_gdr20n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr20r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr25)		\
    U8G_FONT_TABLE_ENTRY(font_gdr25n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr25r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr30)		\
    U8G_FONT_TABLE_ENTRY(font_gdr30n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr30r)		\
    U8G_FONT_TABLE_ENTRY(font_gdr9)		\
    U8G_FONT_TABLE_ENTRY(font_gdr9n)		\
    U8G_FONT_TABLE_ENTRY(font_gdr9r)		\
    U8G_FONT_TABLE_ENTRY(font_helvB08)		\
    U8G_FONT_TABLE_ENTRY(font_helvB08n)		\
    U8G_FONT_TABLE_ENTRY(font_helvB08r)		\
    U8G_FONT_TABLE_ENTRY(font_helvB10)		\
    U8G_FONT_TABLE_ENTRY(font_helvB10n)		\
    U8G_FONT_TABLE_ENTRY(font_helvB10r)		\
    U8G_FONT_TABLE_ENTRY(font_helvB12)		\
    U8G_FONT_TABLE_ENTRY(font_helvB12n)		\
    U8G_FONT_TABLE_ENTRY(font_helvB12r)		\
    U8G_FONT_TABLE_ENTRY(font_helvB14)		\
    U8G_FONT_TABLE_ENTRY(font_helvB14n)		\
    U8G_FONT_TABLE_ENTRY(font_helvB14r)		\
    U8G_FONT_TABLE_ENTRY(font_helvB18)		\
    U8G_FONT_TABLE_ENTRY(font_helvB18n)		\
    U8G_FONT_TABLE_ENTRY(font_helvB18r)		\
    U8G_FONT_TABLE_ENTRY(font_helvB24)		\
    U8G_FONT_TABLE_ENTRY(font_helvB24n)		\
    U8G_FONT_TABLE_ENTRY(font_helvB24r)		\
    U8G_FONT_TABLE_ENTRY(font_helvR08)		\
    U8G_FONT_TABLE_ENTRY(font_helvR08r)		\
    U8G_FONT_TABLE_ENTRY(font_helvR10)		\
    U8G_FONT_TABLE_ENTRY(font_helvR10r)		\
    U8G_FONT_TABLE_ENTRY(font_helvR12)		\
    U8G_FONT_TABLE_ENTRY(font_helvR12r)		\
    U8G_FONT_TABLE_ENTRY(font_helvR14)		\
    U8G_FONT_TABLE_ENTRY(font_helvR14r)		\
    U8G_FONT_TABLE_ENTRY(font_helvR18)		\
    U8G_FONT_TABLE_ENTRY(font_helvR18r)		\
    U8G_FONT_TABLE_ENTRY(font_helvR24)		\
    U8G_FONT_TABLE_ENTRY(font_helvR24n)		\
    U8G_FONT_TABLE_ENTRY(font_helvR24r)		\
    U8G_FONT_TABLE_ENTRY(font_lucasfont_alternate)		\
    U8G_FONT_TABLE_ENTRY(font_lucasfont_alternaten)		\
    U8G_FONT_TABLE_ENTRY(font_lucasfont_alternater)		\
    U8G_FONT_TABLE_ENTRY(font_m2icon_5)		\
    U8G_FONT_TABLE_ENTRY(font_m2icon_7)		\
    U8G_FONT_TABLE_ENTRY(font_m2icon_9)		\
    U8G_FONT_TABLE_ENTRY(font_micro)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB08)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB08r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB10)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB10r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB12)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB12r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB14)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB14r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB18)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB18r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB24)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB24n)		\
    U8G_FONT_TABLE_ENTRY(font_ncenB24r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR08)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR08r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR10)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR10r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR12)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR12r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR14)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR14r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR18)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR18r)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR24)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR24n)		\
    U8G_FONT_TABLE_ENTRY(font_ncenR24r)		\
    U8G_FONT_TABLE_ENTRY(font_orgv01)		\
    U8G_FONT_TABLE_ENTRY(font_orgv01n)		\
    U8G_FONT_TABLE_ENTRY(font_orgv01r)		\
    U8G_FONT_TABLE_ENTRY(font_osb18)		\
    U8G_FONT_TABLE_ENTRY(font_osb18n)		\
    U8G_FONT_TABLE_ENTRY(font_osb18r)		\
    U8G_FONT_TABLE_ENTRY(font_osb21)		\
    U8G_FONT_TABLE_ENTRY(font_osb21n)		\
    U8G_FONT_TABLE_ENTRY(font_osb21r)		\
    U8G_FONT_TABLE_ENTRY(font_osb26)		\
    U8G_FONT_TABLE_ENTRY(font_osb26n)		\
    U8G_FONT_TABLE_ENTRY(font_osb26r)		\
    U8G_FONT_TABLE_ENTRY(font_osb29)		\
    U8G_FONT_TABLE_ENTRY(font_osb29n)		\
    U8G_FONT_TABLE_ENTRY(font_osb29r)		\
    U8G_FONT_TABLE_ENTRY(font_osb35)		\
    U8G_FONT_TABLE_ENTRY(font_osb35n)		\
    U8G_FONT_TABLE_ENTRY(font_osb35r)		\
    U8G_FONT_TABLE_ENTRY(font_osr18)		\
    U8G_FONT_TABLE_ENTRY(font_osr18n)		\
    U8G_FONT_TABLE_ENTRY(font_osr18r)		\
    U8G_FONT_TABLE_ENTRY(font_osr21)		\
    U8G_FONT_TABLE_ENTRY(font_osr21n)		\
    U8G_FONT_TABLE_ENTRY(font_osr21r)		\
    U8G_FONT_TABLE_ENTRY(font_osr26)		\
    U8G_FONT_TABLE_ENTRY(font_osr26n)		\
    U8G_FONT_TABLE_ENTRY(font_osr26r)		\
    U8G_FONT_TABLE_ENTRY(font_osr29)		\
    U8G_FONT_TABLE_ENTRY(font_osr29n)		\
    U8G_FONT_TABLE_ENTRY(font_osr29r)		\
    U8G_FONT_TABLE_ENTRY(font_osr35)		\
    U8G_FONT_TABLE_ENTRY(font_osr35n)		\
    U8G_FONT_TABLE_ENTRY(font_osr35r)		\
    U8G_FONT_TABLE_ENTRY(font_p01type)		\
    U8G_FONT_TABLE_ENTRY(font_p01typen)		\
    U8G_FONT_TABLE_ENTRY(font_p01typer)		\
    U8G_FONT_TABLE_ENTRY(font_pixelle_micro)		\
    U8G_FONT_TABLE_ENTRY(font_pixelle_micron)		\
    U8G_FONT_TABLE_ENTRY(font_pixelle_micror)		\
    U8G_FONT_TABLE_ENTRY(font_profont10)		\
    U8G_FONT_TABLE_ENTRY(font_profont10r)		\
    U8G_FONT_TABLE_ENTRY(font_profont11)		\
    U8G_FONT_TABLE_ENTRY(font_profont11r)		\
    U8G_FONT_TABLE_ENTRY(font_profont12)		\
    U8G_FONT_TABLE_ENTRY(font_profont12r)		\
    U8G_FONT_TABLE_ENTRY(font_profont15)		\
    U8G_FONT_TABLE_ENTRY(font_profont15r)		\
    U8G_FONT_TABLE_ENTRY(font_profont17)		\
    U8G_FONT_TABLE_ENTRY(font_profont17r)		\
    U8G_FONT_TABLE_ENTRY(font_profont22)		\
    U8G_FONT_TABLE_ENTRY(font_profont22r)		\
    U8G_FONT_TABLE_ENTRY(font_profont29)		\
    U8G_FONT_TABLE_ENTRY(font_profont29r)		\
    U8G_FONT_TABLE_ENTRY(font_robot_de_niro)		\
    U8G_FONT_TABLE_ENTRY(font_robot_de_niron)		\
    U8G_FONT_TABLE_ENTRY(font_robot_de_niror)		\
    U8G_FONT_TABLE_ENTRY(font_symb08)		\
    U8G_FONT_TABLE_ENTRY(font_symb08r)		\
    U8G_FONT_TABLE_ENTRY(font_symb10)		\
    U8G_FONT_TABLE_ENTRY(font_symb10r)		\
    U8G_FONT_TABLE_ENTRY(font_symb12)		\
    U8G_FONT_TABLE_ENTRY(font_symb12r)		\
    U8G_FONT_TABLE_ENTRY(font_symb14)		\
    U8G_FONT_TABLE_ENTRY(font_symb14r)		\
    U8G_FONT_TABLE_ENTRY(font_symb18)		\
    U8G_FONT_TABLE_ENTRY(font_symb18r)		\
    U8G_FONT_TABLE_ENTRY(font_symb24)		\
    U8G_FONT_TABLE_ENTRY(font_symb24r)		\
    U8G_FONT_TABLE_ENTRY(font_timB08)		\
    U8G_FONT_TABLE_ENTRY(font_timB08r)		\
    U8G_FONT_TABLE_ENTRY(font_timB10)		\
    U8G_FONT_TABLE_ENTRY(font_timB10r)		\
    U8G_FONT_TABLE_ENTRY(font_timB12)		\
    U8G_FONT_TABLE_ENTRY(font_timB12r)		\
    U8G_FONT_TABLE_ENTRY(font_timB14)		\
    U8G_FONT_TABLE_ENTRY(font_timB14r)		\
    U8G_FONT_TABLE_ENTRY(font_timB18)		\
    U8G_FONT_TABLE_ENTRY(font_timB18r)		\
    U8G_FONT_TABLE_ENTRY(font_timB24)		\
    U8G_FONT_TABLE_ENTRY(font_timB24n)		\
    U8G_FONT_TABLE_ENTRY(font_timB24r)		\
    U8G_FONT_TABLE_ENTRY(font_timR08)		\
    U8G_FONT_TABLE_ENTRY(font_timR08r)		\
    U8G_FONT_TABLE_ENTRY(font_timR10)		\
    U8G_FONT_TABLE_ENTRY(font_timR10r)		\
    U8G_FONT_TABLE_ENTRY(font_timR12)		\
    U8G_FONT_TABLE_ENTRY(font_timR12r)		\
    U8G_FONT_TABLE_ENTRY(font_timR14)		\
    U8G_FONT_TABLE_ENTRY(font_timR14r)		\
    U8G_FONT_TABLE_ENTRY(font_timR18)		\
    U8G_FONT_TABLE_ENTRY(font_timR18r)		\
    U8G_FONT_TABLE_ENTRY(font_timR24)		\
    U8G_FONT_TABLE_ENTRY(font_timR24n)		\
    U8G_FONT_TABLE_ENTRY(font_timR24r)		\
    U8G_FONT_TABLE_ENTRY(font_tpssb)		\
    U8G_FONT_TABLE_ENTRY(font_tpssbn)		\
    U8G_FONT_TABLE_ENTRY(font_tpssbr)		\
    U8G_FONT_TABLE_ENTRY(font_tpss)		\
    U8G_FONT_TABLE_ENTRY(font_tpssn)		\
    U8G_FONT_TABLE_ENTRY(font_tpssr)		\
    U8G_FONT_TABLE_ENTRY(font_trixel_square)		\
    U8G_FONT_TABLE_ENTRY(font_trixel_squaren)		\
    U8G_FONT_TABLE_ENTRY(font_trixel_squarer)		\
    U8G_FONT_TABLE_ENTRY(font_u8glib_4)		\
    U8G_FONT_TABLE_ENTRY(font_u8glib_4r)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_0_8)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_12_13)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_18_19)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_2_3)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_4_5)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_67_75)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_72_73)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_75r)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_76)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_77)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_78_79)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_86)		\
    U8G_FONT_TABLE_ENTRY(font_unifont_8_9)		\
    U8G_FONT_TABLE_ENTRY(font_unifont)		\
    U8G_FONT_TABLE_ENTRY(font_unifontr)		\
**/

#undef U8G_FONT_TABLE_ENTRY
